### ISSUE TITLE
Sending location instead of text

### ISSUE THREAD

**Issue by Thehokt** [star-inc/star_nepgear_bot#1]
Whenever I try it it send location not text

**Comment by supersonictw** [comment]
Oops, the project is WIP, so everything is not ready yet.

**Comment by supersonictw** [comment]
HI, I'm sorry but that the project will be upgrade to the version for OpenChat(LINE Square), so if you want the protect feature in legacy groups, please turn to use <https://github.com/star-inc/star_yuuki_bot>.
